# DATASCIENCE INTERSHIP - DAY 3
# ENVIRONMENT SETUP
# "NAME" - "MANAV SHARMA"
# Intership :datascience
# company - codomax digital solution 
# task -- Numpy 

In [ ]:
 #numpy
import numpy as np

In [1]:
1. #Create a 1D Array
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("1D Array:")
print(arr)


1D Array:
[10 20 30 40 50]


In [2]:
2.#Create a 2D Array
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("2D Array:")
print(arr)

2D Array:
[[1 2 3]
 [4 5 6]]


In [ ]:
3. #Array Indexing
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("First Element:", arr[0])
print("Last Element:", arr[-1])

First Element: 10
Last Element: 50


In [ ]:
4.# Array Slicing
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])

[20 30 40]


In [ ]:
5. #Addition of Two Arrays
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:")
print(a + b)

Addition:
[5 7 9]


In [6]:
6.# Subtraction, Multiplication and Division
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


In [ ]:
7. #Reshape an Array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


: 